language: scala
scala:
- 2.10.0
before_script:
- "./create_version_info.sh"
script: "./sbt test"
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: heroku
  api_key:
    secure: IAoqyY58wF9XVw6Hk/Kuq0I/zeUeF3mAM+bHPA+8T4btoCFayvDAjYKF1FvuZgDJesnnFJRFLfCaTprHTxrZ1Ki35Ow9b8xtKolLHAVQuMA2QRYuAsIjvyQ8meEfGWEI2Z8CVJiu8mVfIZqcIduq1p9YukDzxZ4wVunr+wjJFM0=
